import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Download, 
  Share2, 
  Trash2, 
  ExternalLink, 
  Search,
  Grid,
  List as ListIcon,
  X,
  Maximize2,
  Copy,
  Check,
  AlertCircle
} from 'lucide-react';
import { collection, query, orderBy, onSnapshot, deleteDoc, doc } from 'firebase/firestore';
import { db, handleFirestoreError, OperationType } from '../lib/firebase';
import { useAuth } from '../contexts/AuthContext';
import { cn } from '../lib/utils';

import { GalleryImage } from '../types';

export default function Gallery() {
  const { user } = useAuth();
  const [images, setImages] = React.useState<GalleryImage[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [searchQuery, setSearchQuery] = React.useState('');
  const [selectedImage, setSelectedImage] = React.useState<GalleryImage | null>(null);
  const [notification, setNotification] = React.useState<{ message: string; type: 'success' | 'error' } | null>(null);
  const [deleteId, setDeleteId] = React.useState<string | null>(null);

  const showNotification = (message: string, type: 'success' | 'error' = 'success') => {
    setNotification({ message, type });
    setTimeout(() => setNotification(null), 3000);
  };

  React.useEffect(() => {
    if (!user) return;

    const galleryRef = collection(db, 'users', user.uid, 'gallery');
    const q = query(galleryRef, orderBy('createdAt', 'desc'));

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const imgs = snapshot.docs.map(doc => {
        const data = doc.data();
        let url = data.url;
        
        // If the image is stored locally, retrieve it
        if (data.isLocal) {
          const localData = localStorage.getItem(`nexus_gallery_${doc.id}`);
          if (localData) {
            url = localData;
          } else {
            // Fallback if local storage was cleared
            url = 'https://picsum.photos/seed/error/800/800?blur=2';
          }
        }

        return {
          id: doc.id,
          ...data,
          url
        };
      }) as GalleryImage[];
      setImages(imgs);
      setLoading(false);
    }, (error) => {
      handleFirestoreError(error, OperationType.LIST, galleryRef.path);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [user]);

  const confirmDelete = async () => {
    if (!user || !deleteId) return;
    const path = `users/${user.uid}/gallery/${deleteId}`;
    try {
      await deleteDoc(doc(db, 'users', user.uid, 'gallery', deleteId));
      // Also clean up local storage
      localStorage.removeItem(`nexus_gallery_${deleteId}`);
      setDeleteId(null);
      showNotification("Vision erased from archives");
    } catch (error) {
      handleFirestoreError(error, OperationType.DELETE, path);
      showNotification("Failed to erase vision", "error");
    }
  };

  const handleDeleteClick = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    setDeleteId(id);
  };

  const handleDownload = async (e: React.MouseEvent, url: string, prompt: string) => {
    e.stopPropagation();
    showNotification("Preparing neural download...");
    
    try {
      // Fetch the image as a blob to bypass CORS download restrictions
      const response = await fetch(url);
      const blob = await response.blob();
      const blobUrl = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = blobUrl;
      link.download = `nexus-vision-${prompt.slice(0, 20).replace(/\s+/g, '-')}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      // Cleanup
      setTimeout(() => URL.revokeObjectURL(blobUrl), 100);
      showNotification("Vision downloaded successfully");
    } catch (error) {
      console.error("Download failed:", error);
      // Fallback to direct link if fetch fails (might still fail due to CORS)
      const link = document.createElement('a');
      link.href = url;
      link.target = '_blank';
      link.download = `nexus-vision.png`;
      link.click();
      showNotification("Download failed, opening in new tab", "error");
    }
  };

  const handleCopyPrompt = (e: React.MouseEvent, prompt: string) => {
    e.stopPropagation();
    navigator.clipboard.writeText(prompt);
    showNotification("Prompt copied to neural link");
  };

  const handleShare = async (e: React.MouseEvent, image: GalleryImage) => {
    e.stopPropagation();
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'NEXUS Generated Vision',
          text: `Check out this AI vision generated by NEXUS: "${image.prompt}"`,
          url: window.location.href
        });
      } catch (err) {
        console.error("Share failed:", err);
      }
    } else {
      navigator.clipboard.writeText(image.url);
      showNotification("Image URL copied to clipboard");
    }
  };

  const filteredImages = images.filter(img => 
    img.prompt.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="h-full flex flex-col p-4 md:p-8 overflow-hidden">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">Neural Gallery</h1>
          <p className="text-nexus-text-dim text-xs md:text-sm mt-1">Your synthesized visual archives</p>
        </div>

        <div className="flex items-center gap-4">
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-nexus-text-dim" />
            <input 
              type="text"
              placeholder="Search prompts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-white/5 border border-white/10 rounded-xl pl-10 pr-4 py-2 text-sm text-white focus:border-nexus-accent outline-none transition-all w-full"
            />
          </div>
        </div>
      </div>

      {loading ? (
        <div className="flex-1 flex items-center justify-center">
          <div className="w-12 h-12 border-4 border-nexus-accent border-t-transparent rounded-full animate-spin neon-glow" />
        </div>
      ) : filteredImages.length === 0 ? (
        <div className="flex-1 flex flex-col items-center justify-center text-center opacity-50">
          <Grid className="w-16 h-16 mb-4 text-nexus-text-dim" />
          <p className="text-lg font-medium">No visions found in archives</p>
          <p className="text-sm text-nexus-text-dim">Start generating images to populate your gallery</p>
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto pr-2 no-scrollbar">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            <AnimatePresence>
              {filteredImages.map((image) => (
                <motion.div
                  key={image.id}
                  layoutId={image.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  onClick={() => setSelectedImage(image)}
                  className="group flex flex-col gap-3 cursor-pointer"
                >
                  <div className="px-1">
                    <p className="text-[10px] font-bold text-nexus-text-dim uppercase tracking-widest mb-1 group-hover:text-nexus-accent transition-colors">Neural Vision</p>
                    <p className="text-xs text-white font-medium line-clamp-1 group-hover:text-nexus-accent transition-colors">{image.prompt}</p>
                  </div>

                  <div className="relative aspect-square rounded-2xl overflow-hidden border border-white/5 group-hover:border-nexus-accent/50 transition-all shadow-xl">
                    <img 
                      src={image.url} 
                      alt={image.prompt} 
                      className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                      referrerPolicy="no-referrer"
                    />
                    
                    {/* Hover Overlay */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity p-4 flex flex-col justify-between">
                      <div className="flex justify-end">
                        <div className="px-2 py-1 rounded-md bg-nexus-accent/20 border border-nexus-accent/30 backdrop-blur-md">
                          <span className="text-[10px] font-bold text-nexus-accent uppercase tracking-tighter">AR {image.aspectRatio || '1:1'}</span>
                        </div>
                      </div>

                      <div className="flex items-center gap-2">
                        <button 
                          onClick={(e) => handleDownload(e, image.url, image.prompt)}
                          className="p-2 rounded-lg bg-white/10 hover:bg-nexus-accent hover:text-nexus-bg transition-all"
                          title="Download"
                        >
                          <Download className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={(e) => handleCopyPrompt(e, image.prompt)}
                          className="p-2 rounded-lg bg-white/10 hover:bg-nexus-accent hover:text-nexus-bg transition-all"
                          title="Copy Prompt"
                        >
                          <Copy className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={(e) => handleShare(e, image)}
                          className="p-2 rounded-lg bg-white/10 hover:bg-nexus-accent hover:text-nexus-bg transition-all"
                          title="Share"
                        >
                          <Share2 className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={(e) => handleDeleteClick(e, image.id)}
                          className="p-2 rounded-lg bg-white/10 hover:bg-red-500 transition-all ml-auto"
                          title="Delete"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </div>
      )}

      {/* Lightbox */}
      <AnimatePresence>
        {selectedImage && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 md:p-12 bg-black/95 backdrop-blur-md"
            onClick={() => setSelectedImage(null)}
          >
            <button 
              className="absolute top-8 right-8 p-3 rounded-full bg-white/10 hover:bg-white/20 text-white z-10"
              onClick={() => setSelectedImage(null)}
            >
              <X className="w-6 h-6" />
            </button>

            <motion.div
              layoutId={selectedImage.id}
              className="relative max-w-5xl w-full h-full flex flex-col md:flex-row gap-8 items-center overflow-y-auto no-scrollbar py-12"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex-1 w-full h-full flex items-center justify-center min-h-[300px]">
                <img 
                  src={selectedImage.url} 
                  alt={selectedImage.prompt} 
                  className="max-w-full max-h-full object-contain rounded-2xl shadow-2xl border border-white/10"
                  referrerPolicy="no-referrer"
                />
              </div>

              <div className="w-full md:w-80 flex flex-col gap-6 flex-shrink-0">
                <div className="glass p-6 rounded-2xl border border-white/10 relative group">
                  <div className="flex justify-between items-center mb-3">
                    <h3 className="text-[10px] uppercase tracking-widest text-nexus-accent font-bold">Neural Prompt</h3>
                    <button 
                      onClick={(e) => handleCopyPrompt(e, selectedImage.prompt)}
                      className="p-1.5 rounded-md bg-white/5 hover:bg-nexus-accent hover:text-nexus-bg transition-all"
                    >
                      <Copy className="w-3 h-3" />
                    </button>
                  </div>
                  <p className="text-sm text-white leading-relaxed">{selectedImage.prompt}</p>
                </div>

                <div className="glass p-6 rounded-2xl border border-white/10">
                  <h3 className="text-[10px] uppercase tracking-widest text-nexus-text-dim font-bold mb-3">Metadata</h3>
                  <div className="space-y-2">
                    <div className="flex justify-between text-xs">
                      <span className="text-nexus-text-dim">Generated</span>
                      <span className="text-white">{new Date(selectedImage.createdAt).toLocaleDateString()}</span>
                    </div>
                    <div className="flex justify-between text-xs">
                      <span className="text-nexus-text-dim">Format</span>
                      <span className="text-white">PNG / {selectedImage.aspectRatio || '1:1'}</span>
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3 mt-auto">
                  <button 
                    onClick={(e) => handleDownload(e, selectedImage.url, selectedImage.prompt)}
                    className="flex items-center justify-center gap-2 py-3 rounded-xl bg-nexus-accent text-nexus-bg font-bold hover:opacity-90 transition-opacity"
                  >
                    <Download className="w-4 h-4" />
                    Download
                  </button>
                  <button 
                    onClick={(e) => handleShare(e, selectedImage)}
                    className="flex items-center justify-center gap-2 py-3 rounded-xl bg-white/10 text-white font-bold hover:bg-white/20 transition-all"
                  >
                    <Share2 className="w-4 h-4" />
                    Share
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Notifications */}
      <AnimatePresence>
        {notification && (
          <motion.div
            initial={{ opacity: 0, y: 50, x: '-50%' }}
            animate={{ opacity: 1, y: 0, x: '-50%' }}
            exit={{ opacity: 0, y: 20, x: '-50%' }}
            className={cn(
              "fixed bottom-8 left-1/2 z-[100] px-6 py-3 rounded-2xl border backdrop-blur-md shadow-2xl flex items-center gap-3",
              notification.type === 'success' 
                ? "bg-nexus-accent/10 border-nexus-accent/20 text-nexus-accent" 
                : "bg-red-500/10 border-red-500/20 text-red-400"
            )}
          >
            {notification.type === 'success' ? <Check className="w-4 h-4" /> : <AlertCircle className="w-4 h-4" />}
            <span className="text-sm font-bold tracking-tight">{notification.message}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Delete Confirmation Modal */}
      <AnimatePresence>
        {deleteId && (
          <div className="fixed inset-0 z-[110] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              className="w-full max-w-sm glass p-8 rounded-3xl border border-red-500/30 shadow-[0_0_50px_rgba(239,68,68,0.1)]"
            >
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-2xl bg-red-500/20">
                  <Trash2 className="w-6 h-6 text-red-500" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white">Erase Vision?</h3>
                  <p className="text-xs text-nexus-text-dim uppercase tracking-widest mt-1">Irreversible Action</p>
                </div>
              </div>
              
              <p className="text-sm text-nexus-text-dim mb-8 leading-relaxed">
                Are you sure you want to permanently delete this synthesized vision from the neural archives?
              </p>

              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteId(null)}
                  className="flex-1 py-3 rounded-xl bg-white/5 border border-white/10 text-white font-bold hover:bg-white/10 transition-all"
                >
                  Cancel
                </button>
                <button
                  onClick={confirmDelete}
                  className="flex-1 py-3 rounded-xl bg-red-500 text-white font-bold hover:bg-red-600 transition-all shadow-lg shadow-red-500/20"
                >
                  Erase
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
